/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/todos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTodos"];
        put?: never;
        post: operations["createTodo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/todos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TodoId"];
            };
            cookie?: never;
        };
        /** 指定したIDのTodoを取得する */
        get: operations["getTodo"];
        /** 指定したIDのTodoを更新する */
        put: operations["updateTodo"];
        post?: never;
        /** 指定したIDのTodoを削除する */
        delete: operations["deleteTodo"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Todo: {
            /** Format: int64 */
            id: number;
            title: string;
            description: string;
            /** Format: date */
            dueDate: string | null;
        };
        TodoInput: {
            title: string;
            description: string;
            /** Format: date */
            dueDate?: string | null;
        };
        ValidationErrorResponse: {
            /** @enum {string} */
            type: "validation_error";
            /** @enum {integer} */
            statusCode: 400;
            error: string;
        };
        ValidationMessageNode: {
            messages: string[];
        };
        NotFoundErrorResponse: {
            /** @enum {integer} */
            statusCode: 404;
            message: string;
            error: string;
        };
        BadRequestResponse: {
            /** @enum {integer} */
            statusCode: 400;
            message: string;
            error: string;
        };
    };
    responses: never;
    parameters: {
        TodoId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listTodos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Todo一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"][];
                };
            };
        };
    };
    createTodo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TodoInput"];
            };
        };
        responses: {
            /** @description 作成されたTodo */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
            /** @description バリデーションエラー */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"] & {
                        message: {
                            title?: components["schemas"]["ValidationMessageNode"];
                            description?: components["schemas"]["ValidationMessageNode"];
                            dueDate?: components["schemas"]["ValidationMessageNode"];
                        };
                    };
                };
            };
        };
    };
    getTodo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TodoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 指定したTodo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
            /** @description IDの形式が不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestResponse"];
                };
            };
            /** @description 指定したIDのTodoが存在しない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundErrorResponse"];
                };
            };
        };
    };
    updateTodo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TodoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TodoInput"];
            };
        };
        responses: {
            /** @description 更新後のTodo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
            /** @description バリデーションエラー、またはIDの形式が不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestResponse"] | (components["schemas"]["ValidationErrorResponse"] & {
                        message: {
                            title?: components["schemas"]["ValidationMessageNode"];
                            description?: components["schemas"]["ValidationMessageNode"];
                            dueDate?: components["schemas"]["ValidationMessageNode"];
                        };
                    });
                };
            };
            /** @description 指定したIDのTodoが存在しない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundErrorResponse"];
                };
            };
        };
    };
    deleteTodo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TodoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 削除成功（レスポンスボディなし） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description IDの形式が不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestResponse"];
                };
            };
            /** @description 指定したIDのTodoが存在しない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundErrorResponse"];
                };
            };
        };
    };
}
